### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by lino-levan** [lino-levan/afterthought#3]
Big projects
- [ ] Add "block state"
- [ ] Rewrite physics engine
    - [ ] Add "entities"
        - [ ] Add player entity
        - [ ] Add items
        - [ ] Add falling block (sand)
- [ ] Make chunk size bigger (32x32x32)
- [ ] Move away from three.js, write a custom renderer in WebGPU
- [ ] Write dedicated client in WebGPU and DWM
- [ ] Move away from Vite

**Comment by ghost** [comment]
Q: what's wrong with vite?

**Comment by lino-levan** [comment]
For a game that essentially is just a canvas element on an html page, it's a bit silly to have the entire overhead of vite. I think it would be cool to rewrite this using a really simple custom made framework.

**Comment by ghost** [comment]
> For a game that essentially is just a canvas element on an html page, it's a bit silly to have the entire overhead of vite. I think it would be cool to rewrite this using a really simple custom made framework.

Fair enough
